name: 'Terraform (Infra)'

on:
  push:
    branches: [ "master" ]
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    #environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: infra
      run: terraform init

    - name: Terraform Plan
      working-directory: infra
      env:
        TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_sql_administrator_login: ${{ secrets.SQL_ADMINISTRATOR_LOGIN }}
        TF_VAR_sql_administrator_login_password: ${{ secrets.SQL_ADMINISTRATOR_LOGIN_PASSWORD }}
      run: terraform plan -input=false

    - name: Terraform Apply
      working-directory: infra
      if: github.ref == 'refs/heads/master'
      env:
        TF_VAR_azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
        TF_VAR_azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        TF_VAR_sql_administrator_login: ${{ secrets.SQL_ADMINISTRATOR_LOGIN }}
        TF_VAR_sql_administrator_login_password: ${{ secrets.SQL_ADMINISTRATOR_LOGIN_PASSWORD }}
      run: terraform apply -auto-approve -input=false